Parser working

diff --git a/env b/env
--- a/env
+++ b/env
@@ -4,3 +4,9 @@ CWD=$(dirname "$0")
 CWD=$(readlink -f $CWD)
 
 export PATH=$PATH:$CWD/node_modules/.bin
+
+if ! [ -x "$(command -v emcc)" ]; then
+    echo 'Error: emscripten is not installed.' >&2
+    echo 'Run "brew install emscripten" and try again' >&2
+    exit 1
+fi
